# Generated by Django 5.0.7 on 2024-10-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0004_alter_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('aoop', 'Advanced Object-Oriented Programming'), ('pfsd', 'Python Full Stack Development'), ('mern', 'MERN Stack Development')], max_length=50)),
                ('section', models.CharField(choices=[('s11', 'Section S11'), ('s12', 'Section S12'), ('s13', 'Section S13'), ('s14', 'Section S14'), ('s15', 'Section S15')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
