# Generated by Django 5.0.7 on 2024-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0002_alter_addcourse_course_alter_addcourse_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
