# Generated by Django 5.0.7 on 2024-10-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_student_username'),
        ('facultyapp', '0003_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advance Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('DBMS', 'Database Management Systems'), ('DSA', 'Data Structures and Algorithms'), ('AI', 'Artificial Intelligence')], max_length=50)),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
